#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username ${DB_USER} --dbname ${DB_NAME} <<-EOSQL
	CREATE DATABASE auth;
	GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
	CREATE DATABASE billing;
	GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
	CREATE DATABASE chat;
	GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
	CREATE DATABASE mailing;
	GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
	CREATE DATABASE memory;
	GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
	CREATE DATABASE notification;
	GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
	CREATE DATABASE shop;
	GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
	CREATE DATABASE story;
	GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
EOSQL