name: Tests

on:
  push:
    branches: ['main']

jobs:
  tests:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Cache yarn dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn test:cov

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          flag-name: run-${{ join(matrix.*, '-') }}
          parallel: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

  coverage:
    needs: tests
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Aggregate coverage
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
          carryforward: 'run-1,run-2,run-3,run-4'
          github-token: ${{ secrets.GITHUB_TOKEN }}
