/**
 * Переменные окружения
 */
export enum ENV {
  COOKIE_SECRET = 'COOKIE_SECRET',
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  DOMAIN = 'DOMAIN',
  ORIGIN = 'ORIGIN',
  DATABASE_URL = 'DATABASE_URL',
  VK_API_URL = 'VK_API_URL',
  VK_API_VERSION = 'VK_API_VERSION',
  VK_ID_ACCESS_KEY = 'VK_ID_ACCESS_KEY',
  VK_ID_SERVICE_KEY = 'VK_ID_SERVICE_KEY',
  ACCESS_TOKEN_SECRET = 'ACCESS_TOKEN_SECRET',
  ACCESS_TOKEN_EXPIRATION = 'ACCESS_TOKEN_EXPIRATION',
  REFRESH_TOKEN_SECRET = 'REFRESH_TOKEN_SECRET',
  REFRESH_TOKEN_EXPIRATION = 'REFRESH_TOKEN_EXPIRATION',
}
