export enum ENV {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  ORIGIN = 'ORIGIN',
  DATABASE_URL = 'DATABASE_URL',
  API_VK_URL = 'API_VK_URL',
  API_VK_VERSION = 'API_VK_VERSION',
  VK_ID_ACCESS_KEY = 'VK_ID_ACCESS_KEY',
  VK_ID_SERVICE_KEY = 'VK_ID_SERVICE_KEY',
  ACCESS_TOKEN_SECRET = 'ACCESS_TOKEN_SECRET',
  ACCESS_TOKEN_EXPIRATION = 'ACCESS_TOKEN_EXPIRATION',
  REFRESH_TOKEN_SECRET = 'REFRESH_TOKEN_SECRET',
  REFRESH_TOKEN_EXPIRATION = 'REFRESH_TOKEN_EXPIRATION',
}
